linters:
  disable-all: true
  enable:
    - deadcode
    - dupl
    - errcheck
    - forbidigo
    - gocognit
    - goconst
    - gocyclo
    - godot
    - gosimple
    - gofmt
    - ineffassign
    - revive
    - staticcheck
    - structcheck
    - unparam
    - unused
    - varcheck
linters-settings:
  forbidigo:
    forbid:
      - '^fmt\.Errorf$'
run:
  timeout: 5m
