name: main
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: make build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Lint
        run: make lint
  check-goreleaser-config:
    name: Check goreleaser.yml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: check -f .goreleaser.yml
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17' ]
        kubernetes: [ '1.21', '1.22', '1.23' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: make test KUBERNETES_VERSION=${{ matrix.kubernetes }}
  dry-run:
    name: Dry-run release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: --snapshot --skip-publish --rm-dist
      - name: Test built containers
        run: make container-structure-test
  tag:
    name: Tag release
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: [build, lint, check-goreleaser-config, test, dry-run]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Tag release
        run: |
          TAG="v$(cat VERSION)"
          git tag ${TAG}
          git push origin ${TAG} || true
